### ISSUE TITLE
waitron does not work on windows launched prior to windowchef

### ISSUE THREAD

**Issue by mitchweaver** [tudurom/windowchef#47]
Steps to reproduce:

Launch a terminal from xinitrc, then windowchef.

Type in the terminal `waitron window_maximize`

Nothing is printed, the terminal is not maximized.

I've also tried it in sxhkd, no effect either.

Am I doing something wrong, or is this a bug?

**Comment by tudurom** [comment]
hi, windowchef doesn't update its internal state when started after certain
windows have been already spawned. that's why it doesn't do anything, the
terminal must be spawned after the window manager starts. you can launch it
in the background with a sleep.

**Comment by mitchweaver** [comment]
Wooo... Well now I sure look dumb.

I had spawned it in my xinitrc as i hadn't had a sxkhdrc yet, I was just wanting to test!

ahaha. Apologies for my ignorance, though if its not in the readme that might be a good thing to add.


----

Aside question, why is this?

![image](https://i.imgur.com/kHSY15Y.png)

**Comment by tudurom** [comment]
i think that it's me who looks dumb because I could implement loading
previously spawned windows and I chose not to AND not document my choice.

Also that thing with... 72% CPU? I have no idea, it might be the process
that executes windowchefrc, double check your script. If it doesn't look
funny, consider opening an issue with the contents of windowchefrc and the
version you're running.
