### ISSUE TITLE
Internal border causes black/transparent border on termite

### ISSUE THREAD

**Issue by palm-tree-i** [tudurom/windowchef#49]
Not sure if other applications are affected but termite is.
Not using internal border causes no issue.

**Comment by tudurom** [comment]
Are you using compton?

**Comment by saucesaft** [comment]
Same issue here, im using compton. Btw i used 2bwm before and had the same issue, but @venam fixed it. I dont know how to solve it or which snippet is sufficient to solve it, but with the 2bwm example is clear that the problem is the window manager, not termite. Thanks!

**Comment by venam** [comment]
Hello @tudurom the way I solved it is by drawing the pixmap using the depth of the window client getting the borders and not the generic depth of the root window.

This is the relevant line in your code: https://github.com/tudurom/windowchef/blob/fc61af7e6c4098731e905285f77bd9ea512179d8/wm.c#L1787

Instead of drawing using a depth of `scr->root_depth` you have to draw using the depth of the `client`.

**Comment by tudurom** [comment]
Thanks @venam for your help!

Sorry everyone for being so late.
