### ISSUE TITLE
Large windows are slow to move with a mouse on a 4K monitor

### ISSUE THREAD

**Issue by ghost** [tudurom/windowchef#61]
Hi Tudor,

Thanks for coding windowchef, it's brilliant. 

I'm experiencing slowness when moving large windows (starting at around 700px wide) on a 4K monitor. The Xorg process is beginning to eat up the CPU. Interestingly resizing seems unaffected and works fast.

Here is a `windowchefrc` extract:

```
waitron wm_config replay_click_on_focus true
waitron wm_config pointer_actions move resize_side resize_corner
waitron wm_config pointer_modifier super
```

Is there any way I can help to debug this?

**Comment by tudurom** [comment]
Hello, sorry for the late reply!

Do you experience this issue in other window managers?

I expect the slowness to appear because of the calculations that the WM does every time a window moves, but this calculations depend only on the coordinates, not on the size of the window.

How do you move the window? With the mouse, or with the keyboard?

**Comment by tudurom** [comment]
The user is deleted, closing...
